# Generated by Django 3.2.4 on 2025-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApp', '0003_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='subject',
        ),
    ]
